import os

IS_PROD = True if os.getenv("IS_PROD") else False

PROJECT_NAME = 'textgenrnn-api'
MODEL_BUCKET_NAME = 'textgenrnn-api-models'
CREDENTIALS_JSON_PATH = 'credentials.json'

TRAINING_EPOCHS = 3
MIN_TRAINING_CHARS = 1000
MAX_TRAINING_CHARS = 30000
MAX_PROMPT_CHARS = 30
MIN_MAX_LENGTH = 15
MAX_MAX_LENGTH = 300
MIN_TEMPERATURE = 0.0
MAX_TEMPERATURE = 1.0
DEFAULT_MAX_LENGTH = 300
DEFAULT_TEMPERATURE = 0.5
